name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Show Docker Info
      run: docker info
    - name: Show docker-compose version
      run: docker-compose version
    - name: Some testing
      run: ip a && date && uname -a && lsb_release -a && cat /etc/resolv.conf && ip route
    - name: Build Dockerfile
      run: docker-compose build
    - name: Startup Docker Containers
      run: docker-compose up -d
    - name: Show running Containers
      run: docker ps
    - name: Inspect Ripe Container
      run: docker inspect ripe-atlas_dockerized_atlas-probe_1
    - name:  Verify Containers are up and running
      run: docker inspect -f '{{.State.Running}}' ripe-atlas_dockerized_atlas-probe_1
    - name: Verify if atlas.service is running
      run: docker exec -t ripe-atlas_dockerized_atlas-probe_1 systemctl status atlas.service -l
    - name: Verify if probe_key is written meaing service is fully started
      run: docker exec -t ripe-atlas_dockerized_atlas-probe_1 cat /var/atlas-probe/etc/probe_key | ssh-keygen -v -y -f /dev/stdin
    - name: ls
      run: docker exec -t ripe-atlas_dockerized_atlas-probe_1 ls -lsah /var/atlas-probe/
    - name: show Volumes
      run: docker volume ls
    - name: Inspect Key Volume
      run: docker volume inspect ripe-atlas_dockerized_atlas-key
    - name: Docker show Key Volume Content
      run: docker volume inspect --format '{{ .Mountpoint }}' ripe-atlas_dockerized_atlas-key | xargs ls -lsah
    - name: Seems that github Actions is not allowing SSH outging.
      run: docker exec -t ripe-atlas_dockerized_atlas-probe_1 cat /var/atlas-probe/status/ssh_err.txt
